// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Blogs Website",
    template: "%s | Blogs Website",
  },
};

export default function RootLayout({ children }) {
  return (
    <div>
      <div>Header (Blogs)</div>
      {/* <h1>MY Root Layout</h1> */}
      {children}
      <div>Footer (Blogs)</div>
    </div>
  );
}
