// export const dynamic = "force-dynamic"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/_context/ThemeContext";
import ClientLayout from "@/_components/ClientLayout";
import Header from "@/_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Blogs Website",
    template: "%s | Blogs Website",
  },
};

export default function RootLayout({ children }) {
  //   const randomnumber = Math.random();
  // console.log(randomnumber);

  // if (randomnumber > 0.5) {
  //   throw new Error("Error Occured");
  // }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <Header />
          <ClientLayout>
            {/* <div>Header (Application)</div> */}
            {/* <h1>MY Root Layout</h1> */}
            {children}
            {/* <div>Footer (Application)</div> */}
          </ClientLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
